### PR TITLE
feat(bmr): Substrate-eth block header verification (#643)

### PR DESCRIPTION
**Pull request by andrii-kl**
Closes #ISSUE-NUMBER

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by MuhammedIrfan** [comment]
@andrii-kl May i know why eth verifier is being moved to /cmd/iconbridge/chain/common, If the plan is to make it generic for all the chains would you mind considering /cmd/iconbridge/common/ as followed in https://github.com/icon-project/icon-bridge/pull/545/files

Also it looks like /cmd/iconbridge/chain/common/substrate-eth/sub_eth_verifier.go and /cmd/iconbridge/chain/common/eth/eth_verifier.go does not have much differences, except for the param types.

As these chains are evm based and Ethereum is part of planned integration It might make sense to move the verifier to /cmd/iconbridge/chain/ethereum and create interface for params so this can be reused among other evm based chains

**Comment by manishbista28** [comment]
@andrii-kl -- I'd like to mention some probable issues. Kindly check and confirm if it's so.

1. I have doubts whether verifier methods that have been packaged into common directory are actually common between chains. To my understanding, implementation of these methods (namely VerifyHeader, VerifyCascadingFields, VerifySeal, etc) is specific to BSC chain's parlia consensus engine & it's configuration. If these methods are not common, separating the chain specific function to a common package may not be beneficial.

2. Secondly, even though a set of chains are evm compatible, it does not guarantee that their block/receipts verification mechanism will be the same. For example, please check Verifier implementation of Harmony chain API to notice that the verifier class fields and its methods are entirely different from BSC's. This difference makes reusing common verifier class largely difficult.

3. Finally, I'd like to suggest creating separate PRs for BSC and substrate-eth related changes if possible. The current PR does not have to deal with BSC chain logic if not necessary.

**Comment by andrii-kl** [comment]
> 

1. Yes, you are right. It's a utility classes for different chains. 
I think we can create common folder inside the **chain** folder instead of creating **common/chainutils** on the higher level.
When I see **common** folder inside **chains** folder it's clear the level of responsibility.

2. You are right, I didn't do it just to limited amount of changes. It require a lot of changes in the BSC module,  so it out of scope this task.
Next step will be remove similar functionality. 

3. It will be our next steps. :)

**Comment by andrii-kl** [comment]
> * Yes, you are right. It's a utility classes for different chains.
>   I think we can create common folder inside the **chain** folder instead of creating **common/chainutils** on the higher level.
>   When I see **common** folder inside **chains** folder it's clear the level of responsibility.
> * You are right, I didn't do it just to limited amount of changes. It require a lot of changes in the BSC module,  so it out of scope this task.
>   Next step will be remove similar functionality.
> * It will be our next steps. :)

1. Yes, you are right. It's a utility classes for different chains.
I think we can create common folder inside the chain folder instead of creating common/chainutils on the higher level.
When I see common folder inside chains folder it's clear the level of responsibility.

2. You are right, I didn't do it just to limited amount of changes. It require a lot of changes in the BSC module, so it out of scope this task.
Next step will be remove similar functionality.

3. It will be our next steps. :)

**Comment by CyrusVorwald-ICON** [comment]
Should this branch be deleted?

**Pull request closed without merging**
